import { defineConfig } from 'vitepress';

const pageGroups = [
  {
    key: 'guide',
    items: [
      ['overview', 'overview'],
      ['gettingStarted', 'getting-started'],
      ['architecture', 'architecture'],
      ['projectStructure', 'project-structure'],
      ['routingAndRoles', 'routing-and-roles'],
      ['configuration', 'configuration'],
    ],
  },
  {
    key: 'features',
    items: [
      ['auth', 'auth'],
      ['student', 'student'],
      ['tutorias', 'tutorias'],
      ['tutor', 'tutor'],
      ['admin', 'admin'],
      ['learning', 'learning'],
      ['chatAndAi', 'chat-and-ai'],
    ],
  },
  {
    key: 'development',
    items: [
      ['conventions', 'conventions'],
      ['uiSystem', 'ui-system'],
      ['i18n', 'i18n'],
      ['backendIntegration', 'backend-integration'],
      ['testing', 'testing'],
      ['release', 'release'],
    ],
  },
] as const;

const labels = {
  es: {
    guide: 'Guia',
    features: 'Funcionalidades',
    development: 'Desarrollo',
    overview: 'Vision general',
    gettingStarted: 'Primeros pasos',
    architecture: 'Arquitectura',
    projectStructure: 'Estructura del proyecto',
    routingAndRoles: 'Rutas y roles',
    configuration: 'Configuracion',
    auth: 'Autenticacion',
    student: 'Estudiante',
    tutorias: 'Tutorias',
    tutor: 'Tutor',
    admin: 'Administracion',
    learning: 'Aprendizaje',
    chatAndAi: 'Chat e IA',
    conventions: 'Convenciones',
    uiSystem: 'Sistema UI',
    i18n: 'Internacionalizacion',
    backendIntegration: 'Integracion backend',
    testing: 'Pruebas',
    release: 'Build y despliegue',
    outline: 'En esta pagina',
    prev: 'Anterior',
    next: 'Siguiente',
    lastUpdated: 'Ultima actualizacion',
    theme: 'Tema',
    light: 'Cambiar a tema claro',
    dark: 'Cambiar a tema oscuro',
    menu: 'Menu',
    top: 'Volver arriba',
    footer: 'Documentacion tecnica interna del frontend ECIWISE+.',
    search: 'Buscar',
    noResults: 'Sin resultados',
    reset: 'Restablecer busqueda',
    select: 'Seleccionar',
    navigate: 'Navegar',
    close: 'Cerrar',
  },
  en: {
    guide: 'Guide',
    features: 'Features',
    development: 'Development',
    overview: 'Overview',
    gettingStarted: 'Getting started',
    architecture: 'Architecture',
    projectStructure: 'Project structure',
    routingAndRoles: 'Routes and roles',
    configuration: 'Configuration',
    auth: 'Authentication',
    student: 'Student',
    tutorias: 'Tutorships',
    tutor: 'Tutor',
    admin: 'Administration',
    learning: 'Learning',
    chatAndAi: 'Chat and AI',
    conventions: 'Conventions',
    uiSystem: 'UI system',
    i18n: 'Internationalization',
    backendIntegration: 'Backend integration',
    testing: 'Testing',
    release: 'Build and release',
    outline: 'On this page',
    prev: 'Previous',
    next: 'Next',
    lastUpdated: 'Last updated',
    theme: 'Theme',
    light: 'Switch to light theme',
    dark: 'Switch to dark theme',
    menu: 'Menu',
    top: 'Back to top',
    footer: 'Internal technical documentation for the ECIWISE+ frontend.',
    search: 'Search',
    noResults: 'No results',
    reset: 'Reset search',
    select: 'Select',
    navigate: 'Navigate',
    close: 'Close',
  },
  fr: {
    guide: 'Guide',
    features: 'Fonctionnalites',
    development: 'Developpement',
    overview: 'Vue generale',
    gettingStarted: 'Premiers pas',
    architecture: 'Architecture',
    projectStructure: 'Structure du projet',
    routingAndRoles: 'Routes et roles',
    configuration: 'Configuration',
    auth: 'Authentification',
    student: 'Etudiant',
    tutorias: 'Tutorats',
    tutor: 'Tuteur',
    admin: 'Administration',
    learning: 'Apprentissage',
    chatAndAi: 'Chat et IA',
    conventions: 'Conventions',
    uiSystem: 'Systeme UI',
    i18n: 'Internationalisation',
    backendIntegration: 'Integration backend',
    testing: 'Tests',
    release: 'Build et livraison',
    outline: 'Sur cette page',
    prev: 'Precedent',
    next: 'Suivant',
    lastUpdated: 'Derniere mise a jour',
    theme: 'Theme',
    light: 'Passer au theme clair',
    dark: 'Passer au theme sombre',
    menu: 'Menu',
    top: 'Retour en haut',
    footer: 'Documentation technique interne du frontend ECIWISE+.',
    search: 'Rechercher',
    noResults: 'Aucun resultat',
    reset: 'Reinitialiser la recherche',
    select: 'Selectionner',
    navigate: 'Naviguer',
    close: 'Fermer',
  },
  pt: {
    guide: 'Guia',
    features: 'Funcionalidades',
    development: 'Desenvolvimento',
    overview: 'Visao geral',
    gettingStarted: 'Primeiros passos',
    architecture: 'Arquitetura',
    projectStructure: 'Estrutura do projeto',
    routingAndRoles: 'Rotas e papeis',
    configuration: 'Configuracao',
    auth: 'Autenticacao',
    student: 'Estudante',
    tutorias: 'Tutorias',
    tutor: 'Tutor',
    admin: 'Administracao',
    learning: 'Aprendizagem',
    chatAndAi: 'Chat e IA',
    conventions: 'Convencoes',
    uiSystem: 'Sistema UI',
    i18n: 'Internacionalizacao',
    backendIntegration: 'Integracao backend',
    testing: 'Testes',
    release: 'Build e entrega',
    outline: 'Nesta pagina',
    prev: 'Anterior',
    next: 'Proximo',
    lastUpdated: 'Ultima atualizacao',
    theme: 'Tema',
    light: 'Mudar para tema claro',
    dark: 'Mudar para tema escuro',
    menu: 'Menu',
    top: 'Voltar ao topo',
    footer: 'Documentacao tecnica interna do frontend ECIWISE+.',
    search: 'Pesquisar',
    noResults: 'Sem resultados',
    reset: 'Redefinir pesquisa',
    select: 'Selecionar',
    navigate: 'Navegar',
    close: 'Fechar',
  },
  de: {
    guide: 'Leitfaden',
    features: 'Funktionen',
    development: 'Entwicklung',
    overview: 'Ubersicht',
    gettingStarted: 'Erste Schritte',
    architecture: 'Architektur',
    projectStructure: 'Projektstruktur',
    routingAndRoles: 'Routen und Rollen',
    configuration: 'Konfiguration',
    auth: 'Authentifizierung',
    student: 'Studierende',
    tutorias: 'Tutorien',
    tutor: 'Tutor',
    admin: 'Administration',
    learning: 'Lernen',
    chatAndAi: 'Chat und KI',
    conventions: 'Konventionen',
    uiSystem: 'UI-System',
    i18n: 'Internationalisierung',
    backendIntegration: 'Backend-Integration',
    testing: 'Tests',
    release: 'Build und Release',
    outline: 'Auf dieser Seite',
    prev: 'Zuruck',
    next: 'Weiter',
    lastUpdated: 'Zuletzt aktualisiert',
    theme: 'Theme',
    light: 'Zum hellen Theme wechseln',
    dark: 'Zum dunklen Theme wechseln',
    menu: 'Menu',
    top: 'Nach oben',
    footer: 'Interne technische Dokumentation des ECIWISE+ Frontends.',
    search: 'Suchen',
    noResults: 'Keine Ergebnisse',
    reset: 'Suche zurucksetzen',
    select: 'Auswahlen',
    navigate: 'Navigieren',
    close: 'Schliessen',
  },
} as const;

type LocaleKey = keyof typeof labels;

const localePrefixes: Record<LocaleKey, string> = {
  es: '',
  en: '/en',
  fr: '/fr',
  pt: '/pt',
  de: '/de',
};

function pathFor(locale: LocaleKey, section: string, slug: string): string {
  return `${localePrefixes[locale]}/${section}/${slug}`.replace('//', '/');
}

function nav(locale: LocaleKey) {
  const label = labels[locale];
  return [
    { text: label.guide, link: pathFor(locale, 'guide', 'overview') },
    { text: label.features, link: pathFor(locale, 'features', 'auth') },
    { text: label.development, link: pathFor(locale, 'development', 'conventions') },
  ];
}

function sidebar(locale: LocaleKey) {
  const label = labels[locale];
  return pageGroups.map((group) => ({
    text: label[group.key],
    collapsed: false,
    items: group.items.map(([key, slug]) => ({
      text: label[key],
      link: pathFor(locale, group.key, slug),
    })),
  }));
}

function searchTranslations(locale: LocaleKey) {
  const label = labels[locale];
  return {
    button: {
      buttonText: label.search,
      buttonAriaLabel: label.search,
    },
    modal: {
      noResultsText: label.noResults,
      resetButtonTitle: label.reset,
      footer: {
        selectText: label.select,
        navigateText: label.navigate,
        closeText: label.close,
      },
    },
  };
}

function themeConfig(locale: LocaleKey) {
  const label = labels[locale];
  return {
    siteTitle: 'ECIWISE+ Front',
    nav: nav(locale),
    sidebar: sidebar(locale),
    outline: {
      level: [2, 3],
      label: label.outline,
    },
    docFooter: {
      prev: label.prev,
      next: label.next,
    },
    lastUpdated: {
      text: label.lastUpdated,
      formatOptions: {
        dateStyle: 'medium',
        timeStyle: 'short',
      },
    },
    darkModeSwitchLabel: label.theme,
    lightModeSwitchTitle: label.light,
    darkModeSwitchTitle: label.dark,
    sidebarMenuLabel: label.menu,
    returnToTopLabel: label.top,
    footer: {
      message: label.footer,
      copyright: 'Escuela Colombiana de Ingenieria Julio Garavito',
    },
  };
}

export default defineConfig({
  title: 'ECIWISE+ Front',
  description: 'Documentacion tecnica del frontend institucional ECIWISE+',
  lang: 'es-CO',
  cleanUrls: true,
  lastUpdated: true,
  appearance: true,
  markdown: {
    lineNumbers: true,
  },
  themeConfig: {
    search: {
      provider: 'local',
      options: {
        locales: {
          root: { translations: searchTranslations('es') },
          en: { translations: searchTranslations('en') },
          fr: { translations: searchTranslations('fr') },
          pt: { translations: searchTranslations('pt') },
          de: { translations: searchTranslations('de') },
        },
      },
    },
  },
  locales: {
    root: {
      label: 'Espanol',
      lang: 'es-CO',
      title: 'ECIWISE+ Front',
      description: 'Documentacion tecnica del frontend institucional ECIWISE+',
      themeConfig: themeConfig('es'),
    },
    en: {
      label: 'English',
      lang: 'en-US',
      link: '/en/',
      title: 'ECIWISE+ Front',
      description: 'Technical documentation for the ECIWISE+ frontend',
      themeConfig: themeConfig('en'),
    },
    fr: {
      label: 'Francais',
      lang: 'fr-FR',
      link: '/fr/',
      title: 'ECIWISE+ Front',
      description: 'Documentation technique du frontend ECIWISE+',
      themeConfig: themeConfig('fr'),
    },
    pt: {
      label: 'Portugues',
      lang: 'pt-BR',
      link: '/pt/',
      title: 'ECIWISE+ Front',
      description: 'Documentacao tecnica do frontend ECIWISE+',
      themeConfig: themeConfig('pt'),
    },
    de: {
      label: 'Deutsch',
      lang: 'de-DE',
      link: '/de/',
      title: 'ECIWISE+ Front',
      description: 'Technische Dokumentation des ECIWISE+ Frontends',
      themeConfig: themeConfig('de'),
    },
  },
});
